In [5]:
#get help
open? 

SyntaxError: invalid syntax (<ipython-input-5-4516276001ac>, line 2)

In [7]:
Math.cos?

Object `Math.cos` not found.


In [11]:
file_obj = open("1.txt","r")
for line in file_obj:
    print('')
    print (line.strip())


ALLUSERSPROFILE=C:\ProgramData

APPDATA=C:\Users\user\AppData\Roaming

CommonProgramFiles=C:\Program Files\Common Files

CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files

CommonProgramW6432=C:\Program Files\Common Files

COMPUTERNAME=ECHTP-50-07

ComSpec=C:\Windows\system32\cmd.exe

CONDA_DEFAULT_ENV=cuda

CONDA_EXE=C:\ProgramData\Anaconda3\Scripts\conda.exe

CONDA_PREFIX=C:\Users\user\.conda\envs\cuda

CONDA_PROMPT_MODIFIER=(cuda)

CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe

CONDA_SHLVL=1

DriverData=C:\Windows\System32\Drivers\DriverData

FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer

FPS_BROWSER_USER_PROFILE_STRING=Default

GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\

HOMEDRIVE=C:

HOMEPATH=\Users\user

JAVA_HOME=C:\Program Files\Java\jdk1.8.0_181

JMETER_HOME=C:\Program Files\apache-jmeter-3.2\

LOCALAPPDATA=C:\Users\user\AppData\Local

LOGONSERVER=\\ECHTP-50-07

M2_HOME=C:\Program Files\maven

NUMBER_OF_PROCESSORS=8

OneDrive=C:\Users\user\OneDrive


In [12]:
file_obj = open("A.txt","w")
for line in file_obj:
    print('')
    print (line.strip())

UnsupportedOperation: not readable

In [18]:
file_obj = open("1.txt")
data_list = file_obj.readable
for line in data_list: 
    print(line.strip())
file_obj?

ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\user\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=ECHTP-50-07
ComSpec=C:\Windows\system32\cmd.exe
CONDA_DEFAULT_ENV=cuda
CONDA_EXE=C:\ProgramData\Anaconda3\Scripts\conda.exe
CONDA_PREFIX=C:\Users\user\.conda\envs\cuda
CONDA_PROMPT_MODIFIER=(cuda)
CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
CONDA_SHLVL=1
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HOMEDRIVE=C:
HOMEPATH=\Users\user
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_181
JMETER_HOME=C:\Program Files\apache-jmeter-3.2\
LOCALAPPDATA=C:\Users\user\AppData\Local
LOGONSERVER=\\ECHTP-50-07
M2_HOME=C:\Program Files\maven
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\user\OneDrive
OS=Windows_NT
Path=C:\User

In [19]:
#разобрать запись строки в файл !!!!



In [24]:
digits = range(1,11)
with open("second_file_to_write_in.txt", "w") as file_obj:
    file_obj.writelines(digit + '\n' for digit in map(str, digits))

file_obj = open("second_file_to_write_in.txt")
data_list = file_obj.readable
for line in data_list: 
    print(line.strip())
    


TypeError: 'builtin_function_or_method' object is not iterable

In [47]:
import random
fa = open('file_to_write_in_aa.txt', 'a')


aa=[]
for j in range(5):
    a=[random.random()  for i in range(5)]
    for k in a: 
        fa.write(k)
    aa.append(a)
fa.close
print(aa)
bb=[]
for j in range(5):
    b=[random.random()  for i in range(5)]
    bb.append(b)
print(bb)



TypeError: write() argument must be str, not float

In [62]:
import numpy as np
a=np.array([20,30,40,50])
b=np.arange(4)
c= a + b
print(c)

[20 31 42 53]


In [74]:
import numpy as np
a = np.array([1, 2, 3,4])

print(a)

[1 2 3 4]


In [68]:
print(a)

[1 2 3]


In [ ]:
import numpy as np
a = np.array([1, 2, 3,4])

print(a)

In [90]:
#автозаполнение мар=трицы по ф
def f1(i, j):
    return 100 * i + j
np.fromfunction(f1, (3, 4))

array([[  0.,   1.,   2.,   3.],
       [100., 101., 102., 103.],
       [200., 201., 202., 203.],
       [300., 301., 302., 303.]])

In [118]:
import numpy as np
import random as rand
def f1(i, j):
    #return 100 * i +  +rand.random()
    return i*0 +j*0  +rand.random()
a=np.fromfunction(f1, (10, 10))
a = np.random(10)
print(a)
for i in range(10):
    print(a[i:10,i:10])
    print('det')
    print(np.linalg.det(a[i:10,i:10]))
    


TypeError: 'module' object is not callable

In [125]:
import numpy as np
import random as rand
def f1(i, j):
    #return 100 * i +  +rand.random()
    return i*100 +j 
a=np.fromfunction(f1, (10, 10))
a // 100
a > 300


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [134]:
a=np.arange(12)
b=a
print(b is a)
print(a)
b.shape(3,4)
print(b is a)
print(b)

True
[ 0  1  2  3  4  5  6  7  8  9 10 11]


TypeError: 'tuple' object is not callable

In [139]:
a=np.arange(12)
b=a[3:]
print(b is a)
print(b.base is a)

False
True


In [141]:
import numpy as np
import pandas as pd

# импортируем библиотеку datetime для работы с датами
import datetime
from datetime import datetime, date

# Задаем некоторые опции библиотеки pandas, которые 
# настраивают вывод
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', 80)

# импортируем библиотеку matplotlib для построения графиков
import matplotlib.pyplot as plt
%matplotlib inline

In [143]:
s = pd.Series([1, 2, 3, 4,99])
s

0     1
1     2
2     3
3     4
4    99
dtype: int64

In [144]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [145]:
s.values

array([ 1,  2,  3,  4, 99], dtype=int64)

In [146]:
s[1]

2

In [152]:
s = pd.Series([1, 2, 3, 4], 
               index = ['2016-01-01','2016-02-01','2016-03-01','2016-04-01'])
s


2016-01-01    1
2016-02-01    2
2016-03-01    3
2016-04-01    4
dtype: int64